hostname: "localhost"
monitor:
  cpu:
    alert: true
    INTERVAL: 1
    warning: 70%
    threshold: 80%
    notification:
      email: true
      slack: false
  mem:
    INTERVAL: 5
    alert: false
    warning: 40%
    threshold: 50%
    notification:
      email: true
      slack: false
  disk:
    INTERVAL: 5
  net:
    INTERVAL: 5
    alert: false
    upload:
      warning: 40%
      threshold: 50%
      error: 60%
    download:
      warning: 40%
      threshold: 50%
      error: 60%

# Todo:
# * how to monitor logs ? how keep track the last line of log ?
  